import Header from '@/components/Header';
import Footer from '@/components/Footer';
import styles from './layout.module.css';



export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return <html lang="en">
        <body className={styles.body}>
            <Header />
          
          <main className={styles.main}>
        
                {children}   
             
                </main>
             
         <Footer />
            
        </body>
    </html>
}
